# -*- coding: utf-8 -*-
"""Data_wrangling3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qVmzMd5gHB-tRzLFdrFX6Cju9l5KcnIo
"""



import pandas as pd

data={
    'person':[1,2,3,4,5,6],
    'income':[30000, 35000, 50000, 60000, 45000, 55000],
    'Age_Group': ['Young', 'Young', 'Middle-aged', 'Middle-aged', 'Senior', 'Senior']
}

df=pd.DataFrame(data)
statistics= df.groupby('Age_Group')['income'].agg(['mean','median','max','min','std'])
print(statistics)
df['Age_Group_Numeric'] = df['Age_Group'].astype('category').cat.codes
print("\nNumeric Values for Age_Group:", df['Age_Group'].unique())
print("\nNumeric Values for Age_Group:", df['Age_Group_Numeric'].unique())



"""Iris dataset

"""

import pandas as pd

df=pd.read_csv('Iris.csv')

df.head()

df.tail()

setosa=df[df["Species"]=='Iris-setosa']
print(setosa.describe())

from sklearn import preprocessing

import numpy as np

encoder= preprocessing.LabelEncoder()
df['Species']=encoder.fit_transform(df['Species'])

df

df.groupby("Species").agg(['mean','median','max','min','std'])

