# -*- coding: utf-8 -*-
"""Data Wrangling1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z0hHekIa1ZN5D7_Dpne4-LdY9PUNUw86
"""

import pandas as pd

df=pd.read_csv("train.csv")

df.head()

missing=df.isnull().sum()
print("Missing data:",missing)

description=df.describe()
print("Description:",description)

print("Dimensions of the dataframe:",df.shape)

print("Datatypes in the dataframe:",df.dtypes)

df =df.dropna()

df

df["Sex"].replace({'female':0, 'male':1}, inplace=True)

df

df['Embarked'] = df['Embarked'].map({'C': 0, 'Q': 1, 'S': 2})

df

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# Visualize survival rate by gender
sns.barplot(x='Sex', y='Survived', data=df, ci=None)
plt.title('Survival Rate by Gender')
plt.xlabel('Gender (0 = Female, 1 = Male)')
plt.ylabel('Survival Rate')
plt.show()

# Visualize survival rate by ticket class
sns.barplot(x='Pclass', y='Survived', data=df, ci=None)
plt.title('Survival Rate by Ticket Class')
plt.xlabel('Ticket Class')
plt.ylabel('Survival Rate')
plt.show()

# Visualize survival rate by age
sns.histplot(x='Age', hue='Survived', data=df, kde=True, multiple='stack')
plt.title('Survival Rate by Age')
plt.xlabel('Age')
plt.ylabel('Count')
plt.show()

